name: Monitor TcheLoco

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests pandas beautifulsoup4

      - name: Run monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor_tche.py

      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          git add productos_tche_anterior.csv
          
          git diff --cached --quiet || (
            git commit -m "update csv"
            git push
          )
# Forzar reinicio del programador
